image: publysher/hugo

cache:
    paths:
    - /var/cache/apt/archives/

before_script:
  - apt-get -qq install -y git

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
