---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://gitlab-examples.gitlab.io/pages-hugo"
title: "Hugo Blog Template for GitLab Pages"
canonifyurls: true
theme: "Lanyon"
...
