---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://pages.gitlab.io/hugo"
title: "Hugo Blog Template for GitLab Pages"
canonifyurls: true
theme: "Lanyon"
...
