contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
baseurl       = "http://hugo.ramosmd.ml"
title         = "Hugo Blog Template for GitLab Pages"
canonifyurls  = true
theme         = "Lanyon"

[indexes]
  category  = "categories"
